services:
  message-broker:
    image: broker
    build:
      context: ./message-broker
    container_name: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - broker_data:/var/lib/rabbitmq
    networks:
      - broker_network

  id-database:
    image: redis:7.4.2
    container_name: id-database
    ports:
      - "6379:6379"
    volumes:
      - id_data:/data
    command: redis-server --save 600 1 --loglevel warning
    networks:
      - id_network

  id-provider:
    image: id-provider
    build:
      context: ./id-provider
    container_name: id-provider
    ports:
      - "5000:5000"
    networks:
      - id_network

  data-source:
    image: ds-foldseek
    build:
      context: ./data_source
    container_name: data-source
    restart: always
    depends_on:
      - message-broker
      - apache
    ports:
      - "8000:8000"
    volumes:
      - foldseek_data:/app/results
    networks:
      - broker_network

  apache:
    image: apache
    build:
      context: ./results_provider
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - foldseek_data:/usr/local/apache2/htdocs/foldseek

  web-server:
    image: web-server
    container_name: web-server
    build:
      context: ./web-server
    ports:
      - "3000:3000"
    networks:
      - id_network
    depends_on:
      - id-provider
      - message-broker

  provider:
    image: provider
    build:
      context: ./provider
    container_name: provider
    restart: "no"
    depends_on:
      - message-broker
      - data-source
      - web-server
    networks:
      - broker_network
      - id_network

networks:
  broker_network:
  id_network:

volumes:
  broker_data:
  foldseek_data:
  id_data:
