services:
  message-broker:
    image: broker
    build:
      context: ./message-broker
    container_name: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - broker_data:/var/lib/rabbitmq
    networks:
      - broker_network

  data-source:
    image: ds-foldseek
    build:
      context: ./data_source
    container_name: data-source
    restart: always
    depends_on:
      - message-broker
      - apache
    ports:
      - "8000:8000"
    volumes:
      - foldseek_data:/app/results
    networks:
      - broker_network

  apache:
    image: apache
    build:
      context: ./results_provider
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - foldseek_data:/usr/local/apache2/htdocs/foldseek

  provider:
    image: provider
    build:
      context: ./provider
    container_name: provider
    restart: "no"
    depends_on:
      - message-broker
      - data-source
    networks:
      - broker_network

networks:
  broker_network:

volumes:
  broker_data:
  foldseek_data:
