services:
  message-broker:
    build:
      context: ./containers/message-broker/
      #dockerfile: ./containers/message-broker/Dockerfile
    hostname: "message-broker"
    container_name: message-broker
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3

  id-database:
    image: redis:7.4.2
    container_name: id-database
    volumes:
      - redis:/data
    command: redis-server --save 600 1 --loglevel warning
    healthcheck:
      test: redis-cli info
      interval: 30s
      timeout: 30s
      retries: 3

  executor-http-api:
    build:
      context: ./containers/executor-http-api/
    # image: httpd:2.4.63
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - foldseek:/usr/local/apache2/htdocs/ds_foldseek
      - p2rank:/usr/local/apache2/htdocs/ds_p2rank
      - conservation:/usr/local/apache2/htdocs/conservation
      - inputs:/usr/local/apache2/htdocs/inputs
      - tmp:/usr/local/apache2/htdocs/tmp
    command: httpd -D FOREGROUND
    healthcheck:
      test: curl -f http://localhost/server-status?auto
      interval: 30s
      timeout: 30s
      retries: 3

  id-provider:
    build:
      context: ./containers/id-provider/
      #dockerfile: ./containers/id-provider/Dockerfile
    container_name: id-provider
    depends_on:
      - id-database:
          condition: service_healthy
      
    volumes:
      - ./containers/id-provider/id-provider.py:/app/id-provider.py
    command: python -u id-provider.py

  gateway:
    build:
      context: ./
      dockerfile: ./containers/gateway/Dockerfile
    container_name: gateway
    depends_on:
      - http-server:
          condition: service_healthy
    ports:
      - "8081:8081"

  http-server:
    build:
      context: ./containers/http-server/
      #dockerfile: ./containers/http-server/Dockerfile
    container_name: http-server
    depends_on:
      id-provider:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    volumes:
      - tmp:/tmp
      - ./containers/http-server/http-server.py:/app/http-server.py
    #command: python -u http-server.py
    command: gunicorn -w 4 -b :3000 http-server:app

  ds-foldseek:
    build:
      context: ./containers/data-source-executors/
      dockerfile: ./executor-foldseek/Dockerfile
    container_name: ds-foldseek
    restart: always
    depends_on:
      message-broker:
        condition: service_healthy
    volumes:
      - foldseek:/app/results
      - ./containers/data-source-executors/executor-foldseek/foldseek_executor.py:/app/foldseek_executor.py
      - ./containers/data-source-executors/executor-foldseek/post_processor.py:/app/post_processor.py
      - ./containers/data-source-executors/data_format/builder.py:/app/data_format/builder.py
    command: celery --app=celery_worker worker --queues=ds_foldseek --hostname=foldseek_worker --loglevel=debug

  ds-p2rank:
    build:
      context: ./containers/data-source-executors/
      dockerfile: ./executor-p2rank/Dockerfile
    container_name: ds-p2rank
    restart: always
    depends_on:
      message-broker:
        condition: service_healthy
    volumes:
      - p2rank:/app/results
      - ./containers/data-source-executors/executor-p2rank/p2rank_executor.py:/app/p2rank_executor.py
      - ./containers/data-source-executors/executor-p2rank/post_processor.py:/app/post_processor.py
      - ./containers/data-source-executors/data_format/builder.py:/app/data_format/builder.py
    command: celery --app=celery_worker worker --queues=ds_p2rank --hostname=p2rank_worker --loglevel=debug

  conservation:
    build:
      context: ./containers/conservation
    container_name: conservation
    restart: always
    depends_on:
      message-broker:
        condition: service_healthy
    volumes:
      - conservation:/app/results
      - ./containers/conservation/celery_worker.py:/app/celery_worker.py
      - ./containers/conservation/conservation.py:/app/conservation.py
    command: celery --app=celery_worker worker --queues=conservation --hostname=conservation_worker --loglevel=debug

  converter:
    build:
      context: ./containers/converter/
      #dockerfile: ./containers/data-source-executors/executor-foldseek/Dockerfile
    container_name: converter
    restart: always
    depends_on:
      message-broker:
        condition: service_healthy
    volumes:
      - ./containers/converter/converter_executor.py:/app/converter_executor.py
    command: celery --app=celery_worker worker --queues=converter --hostname=converter_worker --loglevel=debug

  metatask:
    build:
      context: ./containers/metatask/
      #dockerfile: ./containers/metatask/Dockerfile
    container_name: metatask
    restart: "always"
    depends_on:
      message-broker:
        condition: service_healthy
      converter:
      conservation:
      ds-foldseek:
      ds-p2rank:
    volumes:
      - inputs:/app/inputs
      - ./containers/metatask/metatask.py:/app/metatask.py
    command: celery --app=metatask worker --queues=metatask --hostname=metatask_worker --loglevel=debug

  flower:
    build: https://github.com/mher/flower.git
    container_name: flower
    environment:
      CELERY_BROKER_URL: "amqp://guest:guest@message-broker:5672"
    depends_on:
      message-broker:
        condition: service_healthy
    ports:
      - "5555:5555"
    command: "celery flower --url_prefix=service/flower"

volumes:
  rabbitmq:
  redis:
  foldseek:
  p2rank:
  inputs:
  conservation:
  tmp:
