services:
  message-broker:
    build:
      context: ./containers/message-broker/
      #dockerfile: ./containers/message-broker/Dockerfile
    hostname: "message-broker"
    container_name: message-broker
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  id-database:
    image: redis:7.4.2
    container_name: id-database
    volumes:
      - redis:/data
    command: redis-server --save 600 1 --loglevel warning

  executor-http-api:
    image: httpd:2.4.63
    container_name: apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - foldseek:/usr/local/apache2/htdocs/foldseek
      - inputs:/usr/local/apache2/htdocs/inputs
    command: httpd -D FOREGROUND

  id-provider:
    build:
      context: ./containers/id-provider/
      #dockerfile: ./containers/id-provider/Dockerfile
    container_name: id-provider
    depends_on:
      - id-database
    volumes:
      - ./containers/id-provider/id-provider.py:/app/id-provider.py
    command: python -u id-provider.py

  gateway:
    build:
      context: ./
      dockerfile: ./containers/gateway/Dockerfile
    container_name: gateway
    depends_on:
      - http-server
    ports:
      - "8081:8081"

  http-server:
    build:
      context: ./containers/http-server/
      #dockerfile: ./containers/http-server/Dockerfile
    container_name: http-server
    depends_on:
      - id-provider
      - message-broker
    volumes:
      - ./containers/http-server/http-server.py:/app/http-server.py
    command: python -u http-server.py

  ds-foldseek:
    build:
      context: ./containers/data-source-executors/executor-foldseek/
      #dockerfile: ./containers/data-source-executors/executor-foldseek/Dockerfile
    container_name: ds-foldseek
    restart: always
    depends_on:
      - message-broker
    volumes:
      - foldseek:/app/results
      - ./containers/data-source-executors/executor-foldseek/ds_foldseek.py:/app/ds_foldseek.py
      - ./containers/data-source-executors/executor-foldseek/post_processor.py:/app/post_processor.py
    command: celery --app=ds_foldseek worker --queues=ds_foldseek --loglevel=debug

  metatask:
    build:
      context: ./containers/metatask/
      #dockerfile: ./containers/metatask/Dockerfile
    container_name: metatask
    restart: "always"
    depends_on:
      - message-broker
      - ds-foldseek
    volumes:
      - inputs:/app/inputs
      - ./containers/metatask/metatask.py:/app/metatask.py
    command: celery --app=metatask worker --queues=metatask --loglevel=debug

volumes:
  rabbitmq:
  redis:
  foldseek:
  inputs:
