name: Docker Integration Tests

on: [push]

jobs:
  run-integration-tests:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose environment
        working-directory: ./src
        run: docker compose up -d --build > /dev/null 2>&1

      - name: Make test script executable
        run: chmod +x ./testing/run_tests.sh

      - name: Run integration tests
        working-directory: ./testing
        run: ./run_tests.sh

      - name: Tear down Docker environment
        if: always()
        working-directory: ./src
        run: docker compose down
